from modules_day8 import add as a, sub as s,hello as h,hello1 as h1

# print(add(7,7))   #Without use of as .....
# print(sub(9,3))   #Without use of as .....
# print(hello())    #Without use of as .....
# print(hello1("Raju")) #Without use of as .....

print(a(7,7))
print(s(9,3))
print(h())
print(h1("Raju"))